# Generated by Django 4.1.2 on 2022-11-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='project',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.CharField(max_length=45),
        ),
    ]
